export const ADD_SONG = "Player/ADD_SONG"
export const DELETE_SONG = "Player/DELETE_SONG"
export const DELETE_SONG_BY_INDEX = "Player/DELETE_SONG_BY_INDEX"
export const SET_INDEX = "Player/SET_INDEX"
export const SET_SONG_SRC = "Player/SET_SONG_SRC"
export const SET_TIMER = "Player/SET_TIMER"
export const CHANGE_SONG_PLAYING = "Player/CHANGE_SONG_PLAYING"
